apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-ex
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: microservice-app
  template:
    metadata:
      labels:
        app: microservice-app
    spec:
      containers:
      - name: ms-container
        image: devsecopstrainer/idream-ms:5
        ports:
          - containerPort: 8081
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "510"
            memory: "510Mi"
